apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: de-api-example #change name of deployment
  labels:
    app: de-api-example #change label of deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: de-api-example #change match Selector
  template:
    metadata:
      labels:
        app: de-api-example #change
    spec:
      containers:
      - name: de-api-example #change
        image: gcr.io/${PROJECT_ID}/${NAME_IMAGE}:${VERSION_IMAGE} #change
        ports:
        - name: de-api-example #change
          containerPort: 9093
          protocol: TCP